paths:
  input_file: D:\Learning\NLP\Projects\scratch_nlp\sample_data\wiki_en\wiki_en.csv
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\bert
dataset:
  num_samples: 128
  val_split: 0.2
  test_split: 0.2
  num_vocab: 256
  num_extra_tokens: 5
  seq_len: 128
  seed: 2023
  batch_size: 16
preprocess:
  randomize: False
  operations: ["lcase", "remalpha"]
  replace_token:
    prediction: 0.15
    mask: 0.8
    random: 0.1
  sentence_pair:
    next: 0.5
model:
  d_model: 64
  d_ff: 128
  num_heads: 8
  num_layers: 4
  dropout: 0.3
train:
  epochs: 10
  lr: 0.001
visualize: True

finetune:
  paths:
    input_file: D:\Learning\NLP\Projects\scratch_nlp\sample_data\squad\squad_v1.json
    pretrain_weights: D:\Learning\NLP\Projects\scratch_nlp\output\bert\best_model_pretrain.pt
  dataset:
    num_topics: 25
    val_split: 0.2
    test_split: 0.2
    seed: 2023
    batch_size: 16
  preprocess:
    randomize: False
    operations: ["lcase"]
  train:
    epochs: 10
    lr: 0.001