paths:
  input_folder: D:\Learning\NLP\Projects\scratch_nlp\sample_data\imdb_reviews\train
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\glove
dataset:
  num_samples: 5
  explore_folder: True
  num_vocab: 100
  context: 4
  seed: 2023
  val_split: 0.2
  batch_size: 64
preprocess:
  operations: [lcase, remalpha, stopwords]
  randomize: False
model:
  embed_dim: 128
  device: cpu
train:
  epochs: 1
  lr: 0.05
  x_max: 100
  alpha: 0.75
visualize: True