paths:
  input_folder: D:\Learning\NLP\Projects\scratch_nlp\sample_data\imdb_reviews\train
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\hmm
dataset:
  num_samples: -1
  test_size: 0.2
  seed: 2023
model:
  output_label: True
visualize: True