paths:
  input_folder: D:\Learning\NLP\Projects\scratch_nlp\data\imdb_reviews\train
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\ngram
dataset:
  num_samples: 20
  explore_folder: True
model:
  output_label: True
  ngram: 5
preprocess:
  operations: [lcase, remalpha, stopwords, stemming]
  randomize: True
visualize: True