paths:
  input_folder: D:\Learning\NLP\Projects\scratch_nlp\data\imdb_reviews\train
  test_folder: D:\Learning\NLP\Projects\scratch_nlp\data\imdb_reviews\test
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\rnn
dataset:
  num_samples: 64
  test_samples: 20
  explore_folder: True
  num_vocab: 100
  seed: 2023
  val_split: 0.2
  batch_size: 16
  seq_len: 100
  num_classes: 2
preprocess:
  operations: [lcase, remalpha, stopwords]
  randomize: False
model:
  embed_dim: 128
  num_layers: 2
  h_dim: [64, 32]
  x_dim: [128, 64, 32]
  clf_dim: [32, 16, 8]
  device: cpu
train:
  epochs: 3
  lr: 0.05
visualize: True