paths:
    input_file: D:\Learning\NLP\Projects\scratch_nlp\data\genius_lyrics\english_lyrics.csv
    output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\transformer
dataset:
  num_samples: 128
  val_split: 0.2
  test_split: 0.2
  num_vocab: 256
  num_extra_tokens: 1
  seq_len: 64
  seed: 2023
  batch_size: 16
preprocess:
  randomize: False
  operations: [lcase, remalpha]
model:
  d_model: 64
  d_ff: 128
  num_heads: 8
  num_layers: 4
  dropout: 0.3
train:
  epochs: 20
  lr: 0.001
  eval_metric: "Perplexity"
  bleu_n: 4
  rouge_n_n: 2
  rouge_s_n: 2
visualize: True