paths:
  input_folder: D:\Learning\NLP\Projects\scratch_nlp\sample_data\imdb_reviews\train
  output_folder: D:\Learning\NLP\Projects\scratch_nlp\output\word2vec
dataset:
  num_samples: 5
  explore_folder: True
  num_vocab: 30
  context: 2
  seed: 2023
  val_split: 0.2
  batch_size: 128
preprocess:
  operations: [lcase, remalpha, stopwords, stemming]
  randomize: False
model:
  embed_dim: 128
  device: cpu
train:
  epochs: 2
  lr: 0.001
visualize: True